name: Create Customer Branch

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Name of the customer branch to create'
        required: true
      use_case:
        description: 'Use case template to use as base'
        required: true
        type: choice
        options:
          - rate_request
          - shipment 

# Add permissions block for the workflow
permissions:
  contents: write

jobs:
  create-customer-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new branch from template
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          git fetch origin template/${{ github.event.inputs.use_case }}
          git checkout -b customer/${{ github.event.inputs.branch_name }} origin/template/${{ github.event.inputs.use_case }}
          git push origin customer/${{ github.event.inputs.branch_name }}
