name: Create Customer Branch

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Name of the customer branch to create'
        required: true
      use_case:
        description: 'Use case template to use as base'
        required: true
        type: choice
        options:
          - standard
          - enterprise
          - custom

jobs:
  create-customer-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create new branch from template
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          git fetch origin ${{{ github.event.inputs.use_case }}}_template
          git checkout -b customer/${{ github.event.inputs.branch_name }} origin/${{{ github.event.inputs.use_case }}}_template
          git push origin customer/${{ github.event.inputs.branch_name }}

      - name: Set branch protection rules
        env:
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          BRANCH_NAME: customer/${{ github.event.inputs.branch_name }}
          REPO: ${{ github.repository }}
        run: |
          curl -X PUT \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GH_TOKEN" \
            https://api.github.com/repos/$REPO/branches/$BRANCH_NAME/protection \
            -d '{
              "required_status_checks": {
                "strict": true,
                "contexts": ["test", "lint"]
              },
              "enforce_admins": true,
              "required_pull_request_reviews": {
                "dismissal_restrictions": {},
                "dismiss_stale_reviews": true,
                "require_code_owner_reviews": true,
                "required_approving_review_count": 1
              },
              "restrictions": null
            }' 